### ISSUE TITLE
HD videók nem működnek

### ISSUE THREAD

**Issue by nXu** [nXu/indadl#11]
Úgy néz ki, hogy az Indavideo nem teszi elérhetővé külföldi IP-vel a HD videókat. A megoldás magyar IP lesz, előbb-utóbb. 

Ha valaki szeretni megdobni egy magyar proxyval, szóljon  :)

**Comment by bleachhun** [comment]
Akkor, ezért nem kapok "tokent" a 720p videokhoz?

**Comment by nXu** [comment]
Milyen Ip-rol probalod? Nekem saját gépről hibátlanul megy, a szerver
francia IPn van, ott nem küld 720p tokent

bleachhun <notifications@github.com> ezt írta (időpont: 2019. dec. 26., Csü
12:49):

**Comment by bleachhun** [comment]
Épp ezt írom, hogy kijátszható a token:
pl:

> http://index2-int.indavideo.hu/indavideo/001/646/939/New_Jerseyi_diak_a_62_eves_tanarra_tamadt.360.mp4?&channel=main-z&zone=int&token=8bca998890e9aa30f1eb4ac7db54ff31

ez  a 360p


> http://index2-int.indavideo.hu/indavideo/001/646/939/New_Jerseyi_diak_a_62_eves_tanarra_tamadt.720.mp4?&channel=main-z&zone=int&token=8bca998890e9aa30f1eb4ac7db54ff31

ez meg a 720p (annyit csináltam, hogy kézzel átírtam a .360.mp4 et .720.mp4)  a 360p Token működik a 720p videóhoz

**Comment by nXu** [comment]
Na az editet nem kaptam meg mailben :)

Köszi a tippet, kipróbálom

**Comment by nXu** [comment]
Működni látszik, köszi!
