### ISSUE TITLE
Nem mukodik

### ISSUE THREAD

**Issue by bleachhun** [nXu/indadl#12]
Inda változtatott valamit, csak pörög a lekeres :( nem tudok ra jönni, hogy mit.

**Comment by fdeyso** [comment]
nem vagyok egy nagy szaki webes cuccokban, de a lenti letolto mukodik, azon se lepodnek meg ha valami IP alapu blookolas lenne mogotte vagy akar a lenti oldal kodjaban van valami segitseg
https://fordownloader.com/indavideo-downloader/

**Comment by bleachhun** [comment]
A script is megkapja az URL csak inda valószínűleg, a 720,1080 lehetőség kivételével az apit is megölte mivel a script várja a további két url.

**Comment by nXu** [comment]
Köszi a jelzést meg a tippeket is, hétvégén lesz időm, ha minden igaz, és rá tudok nézni

**Comment by bleachhun** [comment]
720p index3-int/hu elerhetoek de nehanynak nem lehet tekerni mert kihal.

**Comment by nXu** [comment]
Ha minden igaz megvan, megnézem még pár videóval, aztán deploy :)

**Comment by nXu** [comment]
Javítva.

Amúgy valami fura dolgot csinál az inda, ugyanazzal a kóddal saját gépről ad 360p/720p/1080p videót, szerveren már csak 360p és 1080p van a fenti Adrenalinfüggők videóval. Nem értem.
