### ISSUE TITLE
Eszrevetel az indaval:

### ISSUE THREAD

**Issue by bleachhun** [nXu/indadl#16]
Elerheto a 720p az index3-hu/int cdn en a tobbin nem. 

`$check720 = str_replace("360.mp4","720.mp4",$json->video_url);
$haystack = $check720;
$needle   = "index2-int";
$needle2   = "index1-int";
$needle5   = "index2-hu";
$needle6   = "index1-hu";
$needle3   = "magex5-hu";
$needle4   = "magex2-hu";
$ajjj = "magex3-hu";
$ajjj2 = "magex1-hu";

 if(strpos($haystack, $needle3) !== false) {
            $uj720 = str_replace("magex5-hu","index3-hu",
                $check720
            );}
 
 
                 if(strpos($haystack, $needle6) !== false) {
            $uj720 = str_replace("index1-hu","index3-hu",
                $check720
            );}      
            
                  if(strpos($haystack, $ajjj) !== false) {
            $uj720 = str_replace("magex3-hu","index3-hu",
                $check720
            );}      
            
                 if(strpos($haystack, $ajjj2) !== false) {
            $uj720 = str_replace("magex1-hu","index3-hu",
                $check720
            );}
            
            if(strpos($haystack, $needle5) !== false) {
            $uj720 = str_replace("index2-hu","index3-hu",
                $check720
            );}      
                if(strpos($haystack, $needle4) !== false) {
            $uj720 = str_replace("magex2-hu","index3-hu",
                $check720
            );}     `

Ezt curl el ellenoriztem, hogy mit ad vissza ha 200 ast ad akkor hasznalom ha nem akkor csak 360p

**Comment by nXu** [comment]
Eh, érdekes rendszerük lehet :)

**Comment by bleachhun** [comment]
Igen :D amik az atalass elott voltak fent videók meg hibásak ha bele tekersz kozvetlen akkor eldobja. Amik utána kerulnek fel hibátlanul mennek.

**Comment by bleachhun** [comment]
Az oldalamnak nagy ervagas volt ez az inda baszkodas... de legalabb mostmar 720p is elerheto

**Comment by bleachhun** [comment]
Jut eszembe tudsz valami egyszeru kodot a fenti helyett? Amivel egy lekerdezessel vegig tudok menni ? Mert ha array ba rakom elhasal :(

**Comment by nXu** [comment]
Melyik oldalt csinálod?

Hát nálam így van megoldva, nem nézek semmi CDN-t, ha az Indavideo API ad 720p-t, akkor van, ha nem, nincs:

https://github.com/nXu/indadl/blob/024a469e049d5e6a4e1f0dc20112dd5cf21d1c88/app/AmfResponseParser.php#L10

Röviden:
-  `data.flv_files`-ből kiszedem az URL-eket. Ez valami nagyon régi, flashplayeres időkből származó paraméter, nem is találok már olyan videót, ahol ez lenne, de a biztonság kedvéért bent hagytam.
- Ha nincs `data.flv_files` (szóval kb mindig),, akkor a `data.video_files`-ből szedem ki az URL-eket
- A `360.mp4` / `720p.mp4` / `1080p.mp4` stringek alapján döntöm el, hogy milyen felbontású a videó
- A videókhoz hozzárakom a `data.filesh`-ból a megfelelő tokent

**Comment by bleachhun** [comment]
soulmovie 

áhh értem :D én picit meg füszereztem mivel "wowzat" használok.
