### ISSUE TITLE
indavideo uj URL

### ISSUE THREAD

**Issue by bleachhun** [nXu/indadl#17]
Inda ismét babrált! :D
main-director.indavideo.hu/indavideo/003/359/750/5ec8ea94261473.36101732.360.mp4?&token=bced865329b73096a4759cea65637294 

most már ezt az URL-t használja ami átirányít a megfelelő "CDN" re.

**Comment by nXu** [comment]
Nem igazán látom, nekem most működni látszik a letöltő. 
Tudsz mondani egy videót, ahol látszik, hogy változtattak?

**Comment by bleachhun** [comment]
> Nem igazán látom, nekem most működni látszik a letöltő. 
> 
> Tudsz mondani egy videót, ahol látszik, hogy változtattak?

Úgy nézki időszakos volt. De 10 lekeresbol 2 működik a többi szinten 403 ad. 

Nem értem az indat a videa vissza allt 1080p ra inda még mindig a 360 as fassagat csinálja...

**Comment by fdeyso** [comment]
https://indavideo.hu/video/Azur_Lane_12resz_Magyar_Felirattal_HDVEGE

Tegnap ez nem ment, a 10, 11 ugyanebbol igen

**Comment by nXu** [comment]
Köszi, ez valóban nem jó valamiért, rá fogok nézni

**Comment by bleachhun** [comment]
A vissza kapott ertek is fura dupla ?? Kel kerul bar nem hiszem, hogy ez miatt nem megy. Sot rakat mas inda letolto nem mukodik kiveve egy: https://www.letoltesguru.com/indavideo-video-letoltes ez mukodik es nem tudok ra jonni, hogyan. Osszes hasonlo oldal 403 at ad vissza ez az oldal mindig mukodik. (Igaz 720p nem megy).
