### ISSUE TITLE
Keresési hiba

### ISSUE THREAD

**Issue by HydroxYT** [nXu/indadl#18]
Múltkor volt kettő update azóta egyetlen egy indavideós videót nem töltbe sem 720 sem 360pben
megtudjátok oldani?

**Comment by Ricsike935** [comment]
Sziasztok valami nem passzol a letöltővel 403 hiba mindenhez! valaki tudna valamit mondani ?

**Comment by bleachhun** [comment]
> 
> 
> Múltkor volt kettő update azóta egyetlen egy indavideós videót nem töltbe sem 720 sem 360pben
> megtudjátok oldani?

Jelenleg is dolgozunk, a megoldáson. Sajnos az indavideo oldalán van a gond (jobban mondva nem gond hanem tiltás IP/Lekérés blokkolás) .

**Comment by nXu** [comment]
Remélem, a hétvégén lesz időm vele foglalkozni.

Az Indavideó mostanában nagyon igyekszik keresztbe tenni a letöltőnek, nem szeret minket

**Comment by Ricsike935** [comment]
köszönjük !  tisztelet a munkátokért

**Comment by nXu** [comment]
Hát, kicsit későn, de javítva.

**Comment by nXu** [comment]
Javítva :)

**Comment by HydroxYT** [comment]
a 360o már müködik, de a 720p még mindig nem az lenne a főbb..

**Comment by bleachhun** [comment]
> a 360o már müködik, de a 720p még mindig nem az lenne a főbb..

Amig az indavideo nem teszi vissza a 720p mi se tudunk mit kezdeni vele.

**Comment by nXu** [comment]
@HydroxYT küldj egy linket légyszi, ahol nem megy a 720p.
Random a főoldalról megnéztem ezt: https://indavideo.hu/video/Batman_-_10_erdekes_teny , itt megy a 720p rendesen

**Comment by bleachhun** [comment]
> @HydroxYT küldj egy linket légyszi, ahol nem megy a 720p.
> Random a főoldalról megnéztem ezt: https://indavideo.hu/video/Batman_-_10_erdekes_teny , itt megy a 720p rendesen

Gondolom pro user a az illető ezért elérhető alapból a fogaskerekkel is. 

Gondolom az animekre gondol pl: https://indavideo.hu/video/Kaguya-sama_Love_is_War_2_evad_11resz_Magyar_Felirattal

**Comment by nXu** [comment]
@bleachhun ezt a videót maga az indavideó is 360p-ben jatssza, nincs is fent 720p-ben.

**Comment by HydroxYT** [comment]
Igen az animékre gondoltam, régebben ez ment 720pben a letöltő oldalon de mostmár nem, pl link: https://indavideo.hu/video/HDKONOSUBA_-_Legend_of_Crimson_Magyar_Felirat, nekem itt külföldön levan tiltva az indavideo de a letöltő oldalon keresztül meg tudtam nézni sokkal jobb minőségben mint maga az oldalon azért használtam ezt.

**Comment by bleachhun** [comment]
> Igen az animékre gondoltam, régebben ez ment 720pben a letöltő oldalon de mostmár nem, pl link: https://indavideo.hu/video/HDKONOSUBA_-_Legend_of_Crimson_Magyar_Felirat, nekem itt külföldön levan tiltva az indavideo de a letöltő oldalon keresztül meg tudtam nézni sokkal jobb minőségben mint maga az oldalon vpn használatával azért használtam ezt.

Lelett irva, inda kozpontilag tiltotta, sajnos nem tudunk mit kezdeni vele.
