### ISSUE TITLE
720P lekérdsezési érdekesség

### ISSUE THREAD

**Issue by bleachhun** [nXu/indadl#23]
Hali, biztos :D agyfaszt kapsz már :D 

van egy érdekes BUG/Miss config vagy tudja a bánatos tök.
https://indavideo.hu/video/Jatek_kezenallva <-Nem pro felhasználó 720p1080p elérhető az indadl meg találja mind a 3 formátumot.

https://indavideo.hu/video/Batman_-_10_erdekes_teny <- Pro felh 360-720p indadl szintén működik.

https://indavideo.hu/video/Muhyo_to_Rouji_no_Maho_uritsu_Soudan_Jimusho_2evad_5resz_Magyar_Felirattal <- Anime szintén elérhető 720p vel de az indadl nem találja csak 360p (összes Animénél ezt csinálja)  5let?

**Comment by nXu** [comment]
Megoldva.

Köszi a jelzést meg a teszt URL-eket :)
