### ISSUE TITLE
Ip blokkolás?

### ISSUE THREAD

**Issue by bleachhun** [nXu/indadl#27]
Hali, 
saját szervergép és 000webhost on is csak 360p kapok az indától.

Nálad a 360-720p .

Erre esetleg valami megoldás? Nem szeretnék problémát, hogy a te "apidat" használom igyis elég sok lekérésed van szerintem. 

Lehet azabaj, hogy a Saját szervergépem Német IP a webhost is más? Csakis magyar ip röl kap 720p?

**Comment by nXu** [comment]
Szia

őszintén szólva fogalmam sincs, néha teljesen random működik az Indavideo API. Nekem is van, hogy fejlesztés közben mást kapok, mint a szerveren.
Egyébként az indavideo.nxu.hu magyar IP-ről fut, igen

**Comment by bleachhun** [comment]
Azt tudom, de ezek szerint szures is van az apinal, mennyire nehez megoldani egy “proxy”-t bele? Az oldalam alapja az inda videok es mivel csak 360 at vagyok képes lekérdezni így elég tre. 000webhost ra szórnám szét magamnak hogy ne a te ip det terheljem.

**Comment by nXu** [comment]
@bleachhun Tudsz egy becslést, hogy pl. óránként kb mennyi videót nyitnak meg nálad?

**Comment by bleachhun** [comment]
@nXu Becslés elég nehéz de akár extrém helyzet 200-500 is lehet. Pont ezért használom a Wowzát mert cachel, és így nem URL böl dolgozik utána. Viszont sikerült 3 "magyar" hostinghoz feltenni és egy Load Balance rendszerbe bekötni  így a 200-500 kérés 3 felé megy.

**Comment by nXu** [comment]
Óránként 700 kéréssel nyugodtan megküldhetsz engem is, annyit simán bírnia kell, hacsak az indavideo nem tiltja miatta az IP-t, de nem hiszem. Ha esetleg állítasz valami egyedi user-agentet, azt nagyon megköszönöm.

Ha proxyzni szeretnél, az is relatíve egyszerű, ha van hozzá proxy szervered. Ha nincs, akkor valami magyar szolgáltatónál beüzemelhetsz egyet egyszerűen, én a squidet szeretem: https://www.howtoforge.com/how-to-install-squid-proxy-server-on-ubuntu-2004/

Sima PHP cURL-ben így tudod megadni: https://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy

Ha pl innen copyzol, akkor én guzzle-t használok, annak meg így: http://docs.guzzlephp.org/en/stable/request-options.html#proxy

**Comment by bleachhun** [comment]
Egy könyebb megoldást választottam. 
Haproxy domain -> haproxy (load balance) -> 3url kozt round robin kent üzemel igy barmikor tudom boviteni es ha egy kiesik a tobbi meg el. Ha nálad tiltás van akkor bukom a lekerest a wowzanal. Ezért kérdeztem, hogy maga a script “proxy” tud-e mert magyar ip tennek bele igy kulfoldi tarhelyekre is betudnam üzemelni.

**Comment by golddragon007** [comment]
@bleachhun @nXu Csak olyan videók vannak érintve ebben amit külföldről nem lehet megnézni. Vannak olyan videók amit külföldi IP-vel is 1080p-ben megkapok az apitól, pl ez: https://index.indavideo.hu/video/Csodalatos_erzes mondjuk lehet hogy azért mert a kutyát se érdekel :D. Eddig ahogy észrevettem inkább azok a videók érintettek amiket külföldről alapból nem lehet megnézni mert blokkolva vannak.

**Comment by golddragon007** [comment]
@nXu Te tudsz valamilyen limitről, legfőképpen az oldaladdal kapcsolatban? Rendszerint ilyen üzenetett szoktam kapni: "Video URL could not be retrieved from Indavideo API." ugyan arra a videó URL-re. Ha a saját oldalamon próbálom, akkor minden gond nélkül megkapom, kivéve ugye a HD és FHD urlt, mivel nem magyar IP-ről megy. És azt észrevettem a UI-ról is néha közli, hogy "Kérlek, adj meg egy működő Indavideó URL-t".

**Comment by bleachhun** [comment]
@golddragon007 Pont ezert tettem fel 3 tarhelyre es egy Load Balance al elosztom. Lekeres -> load balance (round robin) -> 3 api. ugye ugy mukodik a load balance hogy egy ip:port alatt round robin metodusban hivja meg az oldalakat. Mind a 3 api oldal magyar tarhelyen van (ingyenesen) :D

**Comment by golddragon007** [comment]
@bleachhun lehet én is azt kell csináljam, bár én nem sokat használom, napi 12-25 kérést eresztek el, de azt egyszerre :D pont most fejeztem be a chrome extension összetaknyolását amivel hotkey segítségével a hovered linkeket eltudom küldeni az aria2 letöltőnek, ha meg esetleg indavideós link, akkor lekérem a indavideo.nxu.hu oldalon keresztül és a legnagyobb felbontás átpasszolom az aria2-nek. Just for fun. Utána meg plexel megnézhetem vagy directbe a local serveremről amit letöltöttem. Ezzel végre egy csomó időt megfogok spórolni remélhetőleg.

**Comment by nXu** [comment]
Na ezt pl nem is tudtam, köszi, el kell kezdenem monitorozni, mikor tilt az Inda.
Őszintén szólva nem tudom, mik a számok nálam, ritkán nézek analitikát.

@bleachhun milyen ingyenes magyar tárhelyet használsz? Nem szívesen fizetnék még több gépért / IP-ért

**Comment by nXu** [comment]
Na megnéztem, az elmúlt 24 órában picit több mint 9000 videó API kérés volt, ezt már azért simán lehet, hogy nem engedi az Inda. Szétnézek a magyar tárhelyek között, szerintem el kell osztanom nekem is a  kéréseket

**Comment by bleachhun** [comment]
@nXu  754566 keres 4 nap alatt nálam. Ezt oszd el 3 al. Mert 3 tarhely van.  Ha gondolod, kooperálhatunk hogy enis megadom az url listámat es te is így dupla oldal mennyiséggel vagyunk ellátva. 

Plusz ha gondolod leírom, en mit használok, proxy ra.

**Comment by golddragon007** [comment]
@bleachhun ez engem is érdekelne, bár lehet, hogy jobb lenne azt a részt privátban megbeszélni, mintsem így publikusan...

**Comment by bleachhun** [comment]
@nXu @golddragon007  hol lenne alkalmas? Discord? Vagy email?

**Comment by golddragon007** [comment]
Nekem mindkettő megfelelő

**Comment by nXu** [comment]
nxu#6491  vagy   nxu@nxu.hu
