### ISSUE TITLE
Egy példával meg tudna dobni valaki?

### ISSUE THREAD

**Issue by error13660** [nXu/indadl#28]
Hello!
Még új vagyok az APIk világában és nem teljsesen értem azt ami a weboldalon van kiirva.
Valaki tudna nekem írni egy példát segítségként?
Nagyon megköszönném!

**Comment by bleachhun** [comment]
Mi a gond pontosan?

**Comment by error13660** [comment]
Amikor a kérdést föltettem még nem igazán tudtam hogy hogyan küldhetnék
adatokat egy API felé mert még kissé új voltam a területen, de azóta már
megkaptam a segítségemet máshonnan.
A választ ettől függetlenül nagyon szépen köszönöm.

bleachhun ***@***.***> ezt írta (időpont: 2021. ápr. 26., Hét
7:51):
