### ISSUE TITLE
HD felbontású videót nem támogat

### ISSUE THREAD

**Issue by golddragon007** [nXu/indadl#3]
Hello,

Úgy néz ki, hogy HD felbontású videót nem támogatja, az összes videónál csak a 360p felbontást adja vissza, még azoknál is ahol tudom, hogy van 720 (url-ben átírva betölti).

**Comment by nXu** [comment]
Szia

Köszi a jelzést. Eredetileg támogatta a HDt, valamit úgy tűnik,
változtattak az Indanal. Amint lesz egy kis időm, beleasom magam.

2018. nov. 18., Vas 19:55 dátummal golddragon007 <notifications@github.com>
ezt írta:

**Comment by nXu** [comment]
#7 megoldotta
