### ISSUE TITLE
Nagyobb felbontású videó

### ISSUE THREAD

**Issue by HiperGabor** [nXu/indadl#4]
Szia!
Nagyon tetszik ez a projekt, köszönjük a munkád!
Abban a témában szeretnék kérdezősködni, hogy nagyobb felbontású videókat, támogat a letöltő?
Mert próbáltam 720p-s videót letölteni de nem sikerült.
Ha esetleg tudsz valamit a témával kapcsolatban, köszönöm válaszod előre is!

Kellemes ünnepeket és köszönettel,
WhiteE~

**Comment by nXu** [comment]
Szia!

Köszi a visszajelzést, bocs, hogy csak most írok, nincs sok időm mostanában.
Jogos a kérdés, annak idején elvileg került a letöltőbe 720p / 1080p támogatás, de mostanában mintha nem működne. Esélyes, hogy az Indavideon változott valami. Amint lesz időm, ránézek.

Boldog Új Évet!

**Comment by nXu** [comment]
#3 ugyanez, ezt zárom

**Comment by HiperGabor** [comment]
Boldog Új Évet, köszönöm a választ, további szép napot!
