### ISSUE TITLE
502 Bad Gateway(tudom, hogy nem github fuggo hiba)

### ISSUE THREAD

**Issue by fdeyso** [nXu/indadl#5]
az oldal par napja bad gateway eleresi hibat produkal.
sajnos a php-hez annyira nem ertek, hogy sajat magamnak hostoljam (de ha valaki segit akkor szivesen megcsinalnam)

**Comment by nXu** [comment]
Szia, köszi hogy jelezted. Holnap ránézek.

2019. jan. 19., Szo 18:50 dátummal fdeyso <notifications@github.com> ezt
írta:

**Comment by nXu** [comment]
Javítva

**Comment by fdeyso** [comment]
Köszi
