### ISSUE TITLE
Újabb védelem? 2022.10 SAO

### ISSUE THREAD

**Issue by PizzaProgram** [nxu/indadl#55]
Úgy tűnik, nem működik a letöltés, azt írja, nincs MIME típusú videó.
[link...](https://indavideo.hu/video/Sword_Art_Online_Progressive_-_Aria_of_a_Starless_Night_-_Magyar_Felirattal)

**Comment by nxu** [comment]
Igen, valamit mókoltak, már több mint egy hónapja, csak még nem igazán tudtam vele foglalkozni sajnos. Jelenleg a letöltő se megy

**Comment by nxu** [comment]
https://github.com/nxu/indadl/issues/56
